### ISSUE TITLE
Timeout on login

### ISSUE THREAD

**Issue by Widly** [floragunncom/search-guard-kibana-plugin#34] opened 2017-06-28 11:46 UTC
Sometimes when i'm trying to login, kibana freezes and after ~15 sec returns code 500. Then, when i press F5, kibana successfully login.
I suppose, that SG trying to login in Private tenant (that disabled), i.e. trying to create special index and fails at this moment. Note, that username has upper-case symbols, maybe ES fails when trying to create index name with upper-case symbols.

kibana.yml:
searchguard.multitenancy.enabled: true
searchguard.multitenancy.tenants.enable_global: false
searchguard.multitenancy.tenants.enable_private: false

ES.log:
[ERROR][c.f.s.c.PrivilegesInterceptorImpl] Timeout creating index

**Comment by jochenkressin** [comment] 2017-06-28 11:54
Might be related or even a duplicate of: https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/11

We're fixing the uppercase problem in the next version of the MT module, until then, unfortunately you need to make sure that the tenant names are lowercase only.

**Comment by Widly** [comment] 2017-06-28 12:36
With lowercase usernames this problem still appears.

**Comment by floragunncom** [comment] 2017-07-12 08:18
@Widly Which Kibana/ES/MT-modul version? 
Do you see this problem also without Search Guard installed?

**Comment by floragunncom** [comment] 2017-07-20 20:58
@Widly ping

**Comment by Widly** [comment] 2017-07-21 14:56
I've deleted search guard kibana plugin(5.4.0-3) and now this problem does not apears. Usually this problem appears after some time, i'll also write about problem state tomorrow.

**Comment by Widly** [comment] 2017-07-22 17:48
Yes, without plugin this problem does not appears, but after plugin installation it has appeared again.

**Comment by floragunncom** [comment] 2017-07-26 13:58
We released a v4 of the multitenancy plugin today. This should fix your timeout problem.

ES 5.4/5.5
http://search.maven.org/remotecontent?filepath=com/floragunn/dlic-search-guard-module-kibana-multitenancy/5.4-4/dlic-search-guard-module-kibana-multitenancy-5.4-4-jar-with-dependencies.jar

ES 5.3
http://search.maven.org/remotecontent?filepath=com/floragunn/dlic-search-guard-module-kibana-multitenancy/5.3-4/dlic-search-guard-module-kibana-multitenancy-5.3-4-jar-with-dependencies.jar

**Comment by floragunncom** [comment] 2017-07-26 14:02
Relates https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/search-guard/IRXs-nurIKg/vNoGcr35AAAJ

**Comment by Widly** [comment] 2017-07-26 15:11
Thanks, i'll test it and write report a bit later.

**Comment by Widly** [comment] 2017-07-28 14:47
Thanks! It has fixed main problem with timeout. But SG still trying to login in Private tenant even it's disabled in kibana.yml.
![image](https://user-images.githubusercontent.com/6812404/28722541-c75de27a-73bc-11e7-8763-1bd96ef921b5.png)

**Comment by floragunncom** [comment] 2017-08-02 15:26
@Widly can you pls file a separate issue for "login in Private tenant even it's disabled in kibana.yml"

**Comment by floragunncom** [comment] 2017-08-03 13:43
fixed with v4 released today

**Closed by floragunncom** 2017-08-03 13:43 UTC
