### ISSUE TITLE
Metricbeat not able to load dashboards into Kibana

### ISSUE THREAD

**Issue by imran-arshad** [floragunncom/search-guard-kibana-plugin#58] opened 2018-01-19 19:26 UTC
I have ELK stack deployed on Docker with SearchGuard enabled, and the searchguard-kibana-plugin installed. ElasticSearch has the Searchguard demo roles and users enabled. 

I am trying to ship Metricbeat logs to my ELK. I have the following configuration in my metricbeat.yml:
```
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "admin"
  password: "admin"

setup.kibana:
  host: "localhost:5601"
  username: "admin"
  password: "admin"
```
So I am basically using the demo `admin` user (which has access to all indices. I also tried with the demo `kibanaserver` user that has access on `.kibana` index).

**The issue is that whenever I run the metricbeat setup step, I get access denied from Kibana. The logs in Metricbeat look like this:**
```
$ ./metricbeat setup

Loaded index template

Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /Users/test/Code/Elastic/metricbeat-6.1.0-darwin-x86_64/kibana: Failed to import index-pattern: Failed to load directory /Users/test/Code/Elastic/metricbeat-6.1.0-darwin-x86_64/kibana/default/index-pattern:

  error loading /Users/test/Code/Elastic/metricbeat-6.1.0-darwin-x86_64/kibana/default/index-pattern/metricbeat.json: 403 Forbidden. Response: {"statusCode":403,"error":"Forbidden","message":"Error: Unauthorized"}
```
The logs in Kibana look like this:
```
{"type":"response","@timestamp":"2018-01-18T22:47:17Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/api/status","method":"get","headers":{"host":"localhost:5601","user-agent":"Go-http-client/1.1","accept":"application/json","content-type":"application/json","accept-encoding":"gzip"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1"},"res":{"statusCode":200,"responseTime":39,"contentLength":9},"message":"GET /api/status 200 39ms - 9.0B"}

{"type":"response","@timestamp":"2018-01-18T22:47:17Z","tags":[],"pid":1,"method":"post","statusCode":403,"req":{"url":"/api/kibana/dashboards/import?force=true","method":"post","headers":{"host":"localhost:5601","user-agent":"Go-http-client/1.1","content-length":"250474","accept":"application/json","content-type":"application/json","kbn-version":"6.1.0","accept-encoding":"gzip"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1"},"res":{"statusCode":403,"responseTime":13,"contentLength":9},"message":"POST /api/kibana/dashboards/import?force=true 403 13ms - 9.0B"}
```
When I use Kibana without SG, the dashboards are imported without any error. It seems like SG is blocking those methods on Kibana. I get the same error with Filebeat too

- Elasticsearch: 6.1.0 
- Kibana: 6.1.0
- SearchGuard: 6.1.0-20
- No enterprise modules enabled

**Comment by simmonHuong** [comment] 2018-01-25 14:52
elasticsearch + filebeat + kibana version : 6.1.1 with the same error
```{"statusCode":403,"error":"Forbidden","message":"Error: Unauthorized"}```


I deal with this problem with disable searchguard and use a new instance of kibana and filebeat,import dashboard with success.
Then i can enable searchguard.

**Comment by floragunncom** [comment] 2018-01-25 14:53
A fix for this is already in the making

**Comment by floragunncom** [comment] 2018-02-01 21:55
@jochenkressin Is this related?
https://groups.google.com/d/msgid/search-guard/a20a5d64-168c-4537-86c0-29f21e6b3bcb%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by jochenkressin** [comment] 2018-02-01 22:18
Yes, it's a different effect, but the root cause is the same.

**Comment by floragunncom** [comment] 2018-02-05 20:24
@jochenkressin could this also be related?
https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/12

**Comment by jochenkressin** [comment] 2018-02-05 20:33
Yes, same one.

**Comment by slima** [comment] 2018-02-06 07:00
is there any way around?

**Comment by jochenkressin** [comment] 2018-02-07 19:01
Fixed with v10 of the [Kibana]((https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22)) plugin, released today.

**Closed by jochenkressin** 2018-02-07 19:01 UTC
Labels: SG6, bug
