### ISSUE TITLE
Kibana login says license has 0 days left when trial has remaining days or enterprise disabled

### ISSUE THREAD

**Issue by uwrob** [floragunncom/search-guard-kibana-plugin#95] opened 2018-04-16 22:40 UTC
* Search Guard and Elasticsearch version: 6.2.3
* Installed and used enterprise modules, if any: DLSFLS, REST_MANAGEMENT_API, AUDITLOG, and MULTITENANCY

Derived from discussion post: [https://groups.google.com/forum/#!topic/search-guard/GkdW304ozho](https://groups.google.com/forum/#!topic/search-guard/GkdW304ozho)

-----------------------------------------------------------------------------------------------------

Hi

When trying to access Kibana, login states there are 0 days left on the trial license when there are remaining days or enterprise is disabled. It also states the following error message:

> An error occurred while checking your credentials, make sure you have an Elasticsearch cluster secured by Search Guard running.

I'm able to use all enterprise functionality on ES end (REST API, etc), just cant login to Kibana. 

**Note- We are passing requests to elasticsearch through a proxy, website:8398 because our certificates are associated with our domain on another instance. So to curl to https://localhost:9200 it must be flaged as insecure, or the following error message gets outputed "curl: (51) SSL: no alternative certificate subject name matches target host name 'localhost'"**

Here are my yml files:

**elasticsearch.yml**
`path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
network.host: 0.0.0.0
searchguard.ssl.transport.pemcert_filepath: website.crt
searchguard.ssl.transport.pemkey_filepath: website.key
searchguard.ssl.transport.pemtrustedcas_filepath: gdroot-g2.crt
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: website.crt
searchguard.ssl.http.pemkey_filepath: website.key
searchguard.ssl.http.pemtrustedcas_filepath: gdroot-g2.crt
searchguard.allow_default_init_sgindex: true
searchguard.authcz.admin_dn:
  \- CN=elementdata,OU=client,O=client,L=test, C=de

searchguard.audit.type: internal_elasticsearch
searchguard.enable_snapshot_restore_privilege: true
searchguard.check_snapshot_restore_write_privileges: true
searchguard.restapi.roles_enabled: ["sg_all_access"]
discovery.zen.minimum_master_nodes: 1
node.max_local_storage_nodes: 3
#searchguard.enterprise_modules_enabled: false`

**kibana.yml**
`server.port: 5601
server.host: 0.0.0.0
elasticsearch.url: https://website:8398
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
server.ssl.enabled: true
server.ssl.certificate: /etc/elasticsearch/website.crt
server.ssl.key: /etc/elasticsearch/website.key
elasticsearch.ssl.certificate: /etc/elasticsearch/website.crt
elasticsearch.ssl.key: /etc/elasticsearch/website.key
elasticsearch.ssl.certificateAuthorities: [ /etc/elasticsearch/gdroot-g2.crt ]
elasticsearch.ssl.verificationMode: full

**Comment by floragunncom** [comment] 2018-04-19 17:42
@jochenkressin @mgustafsson1 can you have a look?

**Comment by jochenkressin** [comment] 2018-04-24 01:50
Already looking ;) so far unable to reproduce. I'm on it.

**Comment by jochenkressin** [comment] 2018-04-24 02:10
So this one here is suspicious:

An error occurred while checking your credentials, make sure you have an Elasticsearch cluster secured by Search Guard running.

It occurs when we try to authenticate the user against the authinfo endpoint, get an error back and it is not 401, but something else, e.g. 500.

So when you try to login to Kibana, can you please have a look at the console (e.g. via chrome developer tools) and see if there is anything suspicous logged?

Also, in the network monitoring, you should see a call to:

http://localhost:5601/api/v1/auth/login

Can you inspect this call and see if you find any more info?

**Comment by rubjurgens** [comment] 2018-04-25 09:35
Hello!

We are having the same issue, but without a proxy and only with the community edition, without any enterprise modules, just by following the instructions and using the install_demo_configuration script.

I had a look in the network monitoring, and there was a 500 on the call http://{example}:5601/api/v1/systeminfo. Are there any logs on the server I could have a look?

Thanks in advance!

**Comment by uwrob** [comment] 2018-04-25 18:30
--------------------Looking at the console--------------------

**When the page loads the following error is outputted to the console:** 
"vendors.bundle.js?v=16588:58 GET https://publicIP:5601/api/v1/systeminfo 500 (Internal Server Error)"

**When trying to authenticate the following error is outputed to the console:** 
"POST https://publicIP:5601/api/v1/auth/login 500 (Internal Server Error)"

--------------------Looking at network monitoring--------------------

**System info request header:**
"Request URL: https://publicIP:5601/api/v1/systeminfo
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: publicIP:5601
Referrer Policy: no-referrer-when-downgrade
cache-control: no-cache
Connection: keep-alive
content-encoding: gzip
content-type: application/json; charset=utf-8
Date: Wed, 25 Apr 2018 18:25:49 GMT
kbn-name: kibana
kbn-version: 6.2.2
Transfer-Encoding: chunked
vary: accept-encoding
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Host: publicIP:5601
kbn-version: 6.2.2
Referer: https://publicIP:5601/login?nextUrl=%2F
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
"

**System info response:**
"{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}"

**The login request header:**
"Request URL: https://publicIP:5601/api/v1/auth/login
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: publicIP:5601
Referrer Policy: no-referrer-when-downgrade
cache-control: no-cache
Connection: keep-alive
content-encoding: gzip
content-type: application/json; charset=utf-8
Date: Wed, 25 Apr 2018 18:14:11 GMT
kbn-name: kibana
kbn-version: 6.2.2
Transfer-Encoding: chunked
vary: accept-encoding
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 39
Content-Type: application/json;charset=UTF-8
Host: publicIP:5601
kbn-version: 6.2.2
Origin: https://publicIP:5601
Referer: https://publicIP:5601/login?nextUrl=%2F
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
{username: "admin", password: "admin"}
password
:
"admin"
username
:
"admin"

**Login response:**
"statusCode: 500, error: "Internal Server Error", message: "An internal server error occurred"}
error
:
"Internal Server Error"
message
:
"An internal server error occurred"
statusCode
:
500"

**Comment by jochenkressin** [comment] 2018-04-28 03:36
Thanks for the detailed information, that helps a lot. In addition, could you @uwrob or @rubjurgens set the Search Guard debug level to DEBUG or even TRACE and then try to reproduce the error? The 500 should come from either ES or SG, so I guess we should see something in the logs. Caution: Setting the logs the debug or trace will produce a lot of output due to the healthchecks that Kibana performs on a regular basis.

I can see why we (wrongly) display a "0 days left" message if the call to /systeminfo fails, and we will fix this. However, there should not be any 500 in the first place.

Thanks for your help!

**Comment by uwrob** [comment] 2018-04-30 19:32
I can do that, but how do I do set Search Guard debug level?

**Comment by jochenkressin** [comment] 2018-04-30 19:50
Sorry for not mentioning, setting the debug level is described here: https://docs.search-guard.com/latest/troubleshooting-tls

**Comment by uwrob** [comment] 2018-05-02 22:01
Viewing the documents in an audit-log index, all documents have the following syntax:

audit_node_id" : "-qPtc1TDSr-LrCI1jEHtPg",
          "audit_request_layer" : "REST",
          "audit_request_exception_stacktrace" : "javax.net.ssl.SSLHandshakeException: General SSLEngine problem\n\tat sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1529)\n\tat sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)\n\tat sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)\n\tat sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)\n\tat javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)\n\tat io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281)\n\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215)\n\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)\n\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)\n\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)\n\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem\n\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)\n\tat sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330)\n\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)\n\tat sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1979)\n\tat sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:237)\n\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)\n\tat sun.security.ssl.Handshaker$1.run(Handshaker.java:992)\n\tat sun.security.ssl.Handshaker$1.run(Handshaker.java:989)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)\n\tat io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1364)\n\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1272)\n\t... 19 more\nCaused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)\n\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)\n\tat sun.security.validator.Validator.validate(Validator.java:260)\n\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)\n\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:279)\n\tat sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:130)\n\tat sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1966)\n\t... 27 more\nCaused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\n\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)\n\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)\n\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)\n\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)\n\t... 33 more\n",
          "audit_format_version" : 3,
          "audit_utc_timestamp" : "2018-05-02T00:18:52.937+00:00",
          "audit_node_host_address" : "172.31.40.166",
          "audit_node_name" : "-qPtc1T",
          "audit_category" : "SSL_EXCEPTION",
          "audit_node_host_name" : "172.31.40.166"

**Comment by jochenkressin** [comment] 2018-05-04 16:53
Now I'm a bit confused ;) What you are seeing in the audit logs are TLS exceptions, and they mean that there's a problem with the certification path from one of the node or client certificates to the root certificate:

`Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If these pop up in the audit logs, they should/must also be visible in the Elasticsearch logfiles. Is thi not the case for you?

It appears the exception happens on REST layer. From your kibana config I can see you configured a TLS certificate that is sent from Kibana to Elasticsearch:

```
elasticsearch.ssl.certificate: /etc/elasticsearch/website.crt
elasticsearch.ssl.key: /etc/elasticsearch/website.key
```

There is a known issue in Kibana that relates to these settings:

https://github.com/elastic/kibana/pull/17804

So just for a test, can you please remove/comment these lines:

```
elasticsearch.ssl.certificate: /etc/elasticsearch/website.crt
elasticsearch.ssl.key: /etc/elasticsearch/website.key
elasticsearch.ssl.certificateAuthorities: [ /etc/elasticsearch/gdroot-g2.crt ]
```

And set the verification mode to "none":

`elasticsearch.ssl.verificationMode: none`

Also, you are using the same certificate for ES and KI, and have hostname verification enabled. Are ES and KI running on the same host? What is/are the hostnames in the SAN section of website.crt?

**Comment by jochenkressin** [comment] 2018-05-04 16:58
Also, if I understand correctly, you say you are routing all request via this configured proxy to ES:

elasticsearch.url: https://website:8398

* Do you see someting in the proxy logs eventually? 
* When the proxy forwards the request to ES, which certificates are used? In other words, do you use ssl_pass_through or does your proxy terminate TLS?

Since you have:

`searchguard.ssl.http.enabled: true`

I suspect you are using ssl_pass_through, right?

**Comment by floragunncom** [comment] 2018-05-31 10:28
Fixed with v13

**Closed by floragunncom** 2018-05-31 10:28 UTC
