### ISSUE TITLE
kibana error log "[index_not_found_exception] no such index"

### ISSUE THREAD

**Issue by simmonHuong** [floragunncom/search-guard-kibana-plugin#66] opened 2018-01-30 10:35 UTC
Hello
elasticsearch,filebeat,kibana version:6.1.1
```kibana error log
error  [10:22:54.066]  [index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" } :: {"path":"/_searchguard/api/permissionsinfo","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"},\"status\":404}"}
    at respond (/home/elk/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/home/elk/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/home/elk/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/home/elk/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
appears when login in kibana.Even thought with this error I can login in,and query.
There is no index name "_searchguard" but a "searchguard"

**Comment by isra17** [comment] 2018-02-02 20:25
You have to use the enterprise bundle to enable the searchguard Rest API (And use the GUI administration).

**Comment by simmonHuong** [comment] 2018-02-07 13:54
Thanks so much.I may ignore this then.It bothered me for several days.

**Comment by jochenkressin** [comment] 2018-02-07 15:01
I need to reopen this since we can't seem to reproduce.

- which exact version of the Kibana plugin do you use
- which browser do you use?

Thanks!

**Comment by brokenthumbs** [comment] 2018-02-14 00:05
I am seeing something similar to @simmonHuong. When I start my Kibana service, the logs show me an error that indicate `index_not_found_exception`.

I am using the most recent Kibana plugin, 6.2.1, as specified here: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22

I am using the community edition of Elasticsearch 6.2.1 as well.

```
docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
docker pull docker.elastic.co/kibana/kibana-oss:6.2.1
```

```
 error  [23:56:48.837]  [index_not_found_exception] no such index, with { resource.type="index_expression" & resource.id="_searchguard" & index_uuid="_na_" & index="_searchguard" } :: {"path":"/_searchguard/api/permissionsinfo","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_expression\",\"resource.id\":\"_searchguard\",\"index_uuid\":\"_na_\",\"index\":\"_searchguard\"},\"status\":404}"}
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by jochenkressin** [comment] 2018-02-14 08:57
While it should not affect Kibana it's not normal to see it in the logs. Which browser and operating system are you using?

**Comment by brokenthumbs** [comment] 2018-02-14 15:55
I'm using a Mac OS High Sierra Version 10.13.2, with Google Chrome Version 64.0.3282.167.

But, it seems that it shows up on the first initial login. I tried using Safari and got the same result.

I'm testing this out by locally launching Kibana through a Docker container, and connecting it to my Elasticsearch cluster. So, each time that I restart my Kibana Docker container, and log in using my browser, I see that error show up.

**Comment by brokenthumbs** [comment] 2018-02-14 15:56
Noting that I am also connecting using `http://localhost` and not `https://localhost`, if that matters.

**Comment by jochenkressin** [comment] 2018-02-14 22:08
Thanks for the info, trying to reproduce it here

**Comment by ming2020** [comment] 2018-03-12 05:16
I am seeing something similar to @simmonHuong, and my search guard configuration GUI is not show after i upgrade to 6.2.2.

**Comment by ilongin** [comment] 2018-03-15 11:47
Same here, and I'm also using http instead of https for REST (searchguard.ssl.http.enabled: false)

**Comment by jochenkressin** [comment] 2018-03-15 12:02
In order to avoid confusion, there are two issues here:

First, the REST API and the config GUI are Enterprise features, so if you run the Community version it's expected that the GUI does not show.

What's not expected is the "index_not_found_exception" in the Kibana logs. The exception is due to the fact that the REST API endpoints starting with "_searchguard/api/" are not enabled, and Elasticsearch then treats it like an index name, which of course does not exist.

While the exception is not supposed to be raised, it should not affect the operation of Kibana.

**Comment by ilongin** [comment] 2018-03-15 12:08
Yes, I just figured out that. When I run enterprise edition there is no error and I can see Search Guard in side bar.

**Comment by willouuu** [comment] 2018-03-22 08:47
Hi,
If GUI and API REST aren't enable in the community edition, please edit https://search-guard.com/wp-content/uploads/2018/03/SG_Licensing-model-overview.pdf, so that we can understand and not spend hours trying to display it...
Thanks

**Comment by floragunncom** [comment] 2018-03-22 09:04
@willouuu sorry for your inconvenience, we will update the docs to make this clear

**Comment by jochenkressin** [comment] 2018-03-22 12:29
Will make it more clear in the PDF, the docs, however, correctly have the "Enterprise" label for the configuration GUI: https://docs.search-guard.com/latest/configuration-gui

**Comment by willouuu** [comment] 2018-03-22 13:37
Thanks ! 
But why not allow the GUI for free license ?

**Comment by jochenkressin** [comment] 2018-03-22 13:49
The GUI is a convenience feature. It actually does not add any new functionality, means you can do everything that the GUI provides (and much more) with the sgadmin command line tool:

https://docs.search-guard.com/latest/sgadmin

The GUI uses the REST API under the hood, so we would need to make that free as well. 

To answer in length: It's quite simple, we have a lot of developers working on Search Guard and Kibana, and they all expect to get paid at the end of the month. So deciding which feature is a paid one and which is a free one is not always easy.

Our philosophy was always to provide a free (as in free beer) and fully functional version of Search Guard that covers all basic security needs, like TLS, role based access control, index level security, proxy and PKI support, HTTP Basic authentication etc. That's the Apache2 licensed Community Edition which everyone can use, fork and modify at absolutely no cost. And make our complete code, including the Enterprise features, Open Code. The actual Kibana plugin is licensed under Apache2 as well.

In order to being able to provide this free version also in future, we need to make sure to cover the development, test, release etc. cost. That's why we decided on a dual licensing model.

**Comment by willouuu** [comment] 2018-03-22 14:08
Thank you for your explanations, I understand.
I might ask a quote next year, but I will only use GUI and maybe LDAP

**Comment by jochenkressin** [comment] 2018-04-03 21:39
Fixed with Search Guard v22 and Kibana Plugin v11: https://docs.search-guard.com/latest/changelog-6-x-22

**Closed by jochenkressin** 2018-04-03 21:39 UTC
Labels: website
