### ISSUE TITLE
ace.require is not a function

### ISSUE THREAD

**Issue by floragunncom** [floragunncom/search-guard-kibana-plugin#80] opened 2018-02-26 09:49 UTC
Track: https://github.com/floragunncom/search-guard/issues/452

**Comment by jochenkressin** [comment] 2018-02-27 09:00
Seems like an Kibana bug: https://discuss.elastic.co/t/6-2-0-starts-with-error/118706

**Comment by brano-tichy** [comment] 2018-02-27 09:43
most probably.
i logged [it here](https://github.com/elastic/kibana/issues/16866)
the problem is caused by "Optimizing and caching browser bundles..." step
when the kibana is installed in certain locations
(```c:\Users\255294\AppData\Local\Temp\_ES``` was ok, ```c:\Users\255294\.bin\ES``` caused fatal error, ```./optimize/bundles/*.bundle.js``` files differed)

**Comment by jochenkressin** [comment] 2018-04-03 21:38
This is a Kibana issue, closing it here.

**Closed by jochenkressin** 2018-04-03 21:38 UTC

**Comment by callahan22** [comment] 2018-05-08 19:47
Just an FYI for anyone else ending up here looking for a solution to the above problem.
The solution is to install the search-guard-kibana-plugin through Powershell not the cmd.
Once it's done this way, start up Kibana.bat from within the same Powershell window and test.
Once you've confirmed that works, you can terminate the process in PS and go back to running it as a service or however you used to start it up.
