### ISSUE TITLE
Is there a way to authenticate against the plugin?

### ISSUE THREAD

**Issue by sergibondarenko** [floragunncom/search-guard-kibana-plugin#42] opened 2017-10-03 12:57 UTC
Basic authentication doesn't work.
```
https://user:password@kibana:5601
```
I need this for my Kibana plugin which goes to a dashboard, does a screenshot of it and send the image by email.

**Comment by floragunncom** [comment] 2017-10-04 10:36
Duplicate of https://github.com/floragunncom/search-guard-kibana-plugin/issues/37

**Closed by floragunncom** 2017-10-04 10:36 UTC
