### ISSUE TITLE
Kibana failed to login in SearchGuard GUI

### ISSUE THREAD

**Issue by lyeesim988** [floragunncom/search-guard-kibana-plugin#98] opened 2018-06-08 00:44 UTC
Hi I have this error when I tried to login with kibanaserver after the search-guard kibana plugin installation.

![gui](https://user-images.githubusercontent.com/38025718/41132963-b567ccc0-6af6-11e8-90b2-e30182f82b9b.png)

I have 2 nodes which are the aws instances, the certificates are generated by offline TLS tool.
The kibana is installed on another client and point to node1.

My kibana.yml

```
# Kibana is served by a back end server. This setting specifies the port to use.
#server.port: 5601

# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
#server.host: "localhost"

# Enables you to specify a path to mount Kibana at if you are running behind a proxy. This only affects
# the URLs generated by Kibana, your proxy is expected to remove the basePath value before forwarding requests
# to Kibana. This setting cannot end in a slash.
#server.basePath: ""

# The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: 1048576

# The Kibana server's name.  This is used for display purposes.
#server.name: "your-hostname"

# The URL of the Elasticsearch instance to use for all your queries.
elasticsearch.url: "https://126.21.33.72:9200/"

# When this setting's value is true Kibana uses the hostname specified in the server.host
# setting. When the value of this setting is false, Kibana uses the hostname of the host
# that connects to this Kibana instance.
#elasticsearch.preserveHost: true

# Kibana uses an index in Elasticsearch to store saved searches, visualizations and
# dashboards. Kibana creates a new index if the index doesn't already exist.
#kibana.index: ".kibana"

# The default application to load.
#kibana.defaultAppId: "home"

# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
#elasticsearch.username: "user"
#elasticsearch.password: "pass"
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the Kibana server to the browser.
#server.ssl.enabled: false
#server.ssl.certificate: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files validate that your Elasticsearch backend uses the same key files.
#elasticsearch.ssl.certificate: /path/to/your/client.crt
#elasticsearch.ssl.key: /path/to/your/client.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your Elasticsearch instance.
#elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
#elasticsearch.ssl.verificationMode: full

# Time in milliseconds to wait for Elasticsearch to respond to pings. Defaults to the value of
# the elasticsearch.requestTimeout setting.
#elasticsearch.pingTimeout: 1500

# Time in milliseconds to wait for responses from the back end or Elasticsearch. This value
# must be a positive integer.
#elasticsearch.requestTimeout: 30000

# List of Kibana client-side headers to send to Elasticsearch. To send *no* client-side
# headers, set this value to [] (an empty list).
#elasticsearch.requestHeadersWhitelist: [ authorization ]

# Header names and values that are sent to Elasticsearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
#elasticsearch.customHeaders: {}

# Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
#elasticsearch.shardTimeout: 0

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
#elasticsearch.startupTimeout: 5000

# Specifies the path where Kibana creates the process ID file.
#pid.file: /var/run/kibana.pid

# Enables you specify a file where Kibana stores log output.
#logging.dest: stdout

# Set the value of this setting to true to suppress all logging output.
#logging.silent: false

# Set the value of this setting to true to suppress all logging output other than error messages.
#logging.quiet: false

# Set the value of this setting to true to log all events, including system usage information
# and all requests.
#logging.verbose: false

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000.
#ops.interval: 5000

# The default locale. This locale can be used in certain circumstances to substitute any missing
# translations.
#i18n.defaultLocale: "en"
tilemap.url: https://a.tile.openstreetmap.org/{z}/{x}/{y}.png
tilemap.options.minZoom: 0
tilemap.options.maxZoom: 20
```
My elasticsearch.yml

```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: mycluster
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: ["126.21.33.72", "126.21.31.70"]

#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes:
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
searchguard.ssl.transport.pemcert_filepath: node1.pem
searchguard.ssl.transport.pemkey_filepath: node1.key
searchguard.ssl.transport.pemkey_password: EW8i329pL1
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: node1_http.pem
searchguard.ssl.http.pemkey_filepath: node1_http.key
searchguard.ssl.http.pemkey_password: Rg43sij90L
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.nodes_dn:
- CN=node1.example.com,OU=Ops,O=example Com\, Inc.,DC=example,DC=com
- CN=node2.example .com,OU=Ops,O=example Com\, Inc.,DC=example,DC=com
searchguard.authcz.admin_dn:
- CN=kirk.example.com,OU=Ops,O=Example Com\, Inc.,DC=example,DC=com
searchguard.restapi.roles_enabled: ["sg_all_access", ...]
searchguard.enterprise_modules_enabled: false
```
For:
https://126.21.33.72:9200/_searchguard/authinfo
```
{"user":"User [name=admin, roles=[admin], requestedTenant=null]","user_name":"admin","user_requested_tenant":null,"remote_address":"112.207.17.41:43812","backend_roles":["admin"],"custom_attribute_names":["attr.internal.attribute1","attr.internal.attribute2","attr.internal.attribute3"],"sg_roles":["sg_all_access","sg_own_index"],"sg_tenants":{"admin_tenant":true,"admin":true},"principal":null,"peer_certificates":"0"}
```

https://126.21.33.72:9200/_searchguard/health
```
{"message":null,"mode":"strict","status":"UP"}
```

kibana version: 6.2.2
kibana search guard plugin: 6.2.2-13
Elasticsearch version on nodes: 6.2.4

Does anyone has similar issue or advise me on how to solve this? 
Thanks in advance!

**Comment by floragunncom** [comment] 2018-06-09 16:43
If you have generated self-signed certificates with the TLS tool, you need to either disable certificate verification by setting:

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
elasticsearch.ssl.verificationMode: none

Or you need to configure your root CA in Kibana:

elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]

Otherwise, certificate validation fails. 
This error should also lead to an entry in the Kibana logs, do you see something there?

**Comment by lyeesim988** [comment] 2018-06-11 07:36
Hi thank you for the advice. I greatly appreciate it. It works after I insert this line to kibana.yml as you suggested:
```
elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]
```
Then, I get the constant redirection to login page without error message so I set kibana to accept unsecure HTTP by:

```
searchguard.cookie.secure: false
```

The login is fine now but I did not see the Search Guard entry in the left navigation pane.

![1](https://user-images.githubusercontent.com/38025718/41218150-b6b9ee58-6d8c-11e8-9b02-5a9b8db49612.png)

Am i missing out configuration in sg_roles or sg_mapping_roles? 
I am now using login: kibanaserver and pwd: kibanaserver.

Thanks.

**Comment by floragunncom** [comment] 2018-06-12 18:03
Will close this because it's not an issue. Pls ask questions here: https://groups.google.com/forum/#!forum/search-guard

**Closed by floragunncom** 2018-06-12 18:03 UTC

**Comment by RodKWATE** [comment] 2018-07-12 02:49
I have the same problem but no solution . Can you help me ? Thank you

**Comment by floragunncom** [comment] 2018-07-12 07:08
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
